# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        # Require coverage to not drop by more than 2%
        threshold: 2%
    patch:
      default:
        # Require 50% coverage on new code
        target: 50%

# Ignore generated files and test files in coverage reports
ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mocks/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
