name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: sreq version
      description: Run `sreq --version` to get this
      placeholder: v0.1.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider (if applicable)
      options:
        - Consul
        - AWS Secrets Manager
        - Not provider-related
        - Other

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: |
        I ran `sreq run -s my-service GET /health` and got an unexpected error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: |
        I expected the request to succeed and return the health status...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `sreq init`
        2. Configure service in config.yaml
        3. Run `sreq run -s my-service GET /health`
        4. See error
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Relevant parts of your config.yaml (remove sensitive data!)
      render: yaml
      placeholder: |
        providers:
          consul:
            address: "consul.internal:8500"
        services:
          my-service:
            environments:
              dev:
                provider: consul
                path: "services/my-service/dev"

  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      description: Any error messages or relevant output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or information
